### ISSUE TITLE
能不能降级到C++11依赖？

### ISSUE THREAD

**Issue by MirrorYuChen** [ChunelFeng/CThreadPool#1]

**Comment by MirrorYuChen** [comment]
老哥，如题~能不能降级都C++11依赖？

**Comment by ChunelFeng** [comment]
我看了一下，需要改动两点：
1，将工程中，所有的 std::make_unique<T> 改成直接 new std::unique_ptr<T>
2，删除工程中，所有 enable_if_t 模板限定。

应该就可以了。

有强诉求的话，私聊。不太想在 repo中支持了 😂

**Comment by ChunelFeng** [comment]
或者自己封装一个dll，然后写 cpp11的程序调用起来也可以哦 😋

**Comment by MirrorYuChen** [comment]
可以的，收到，谢谢老哥！很实用的模块，哈哈哈，嫖了嫖了！
