### ISSUE TITLE
UThreadPool.inl中commit函数线程安全问题有疑问

### ISSUE THREAD

**Issue by xiaolaosao** [ChunelFeng/CThreadPool#5]
请问线程池在使用的时候，是创建后，仅单个线程通过线程池向任务队列中commit任务吗？
这个commit函数中间有一个dispatch函数用于按我们的思路分配任务到线程本地任务队列/线程池的任务队列，如果是多个线程用线程池commit任务，会存在线程安全问题吧？

**Comment by xiaolaosao** [comment]
比方说，当设置主线程数量为最大线程数量时，理论上dispatch会让线程池commit任务时全部放到工作线程本地任务队列，而我使用多个线程一起提交任务的时候，不给dispatch这里加锁的话会将一小部分任务提交到线程池中的任务队列中。所以这块有些疑问

**Comment by ChunelFeng** [comment]
无论是 thread内部的queue，还是 pool内部的queue，其中的任务，都可以被执行。并不会有您提到的线程安全问题。

主thread执行任务的顺序是：local->pool->steal ，
辅助thread执行任务的顺序是：pool 
所以，无论任务被 dispatch到哪里，都是可以执行到的。
之所以提供 dispatch方法（虚方法），是供使用者自己实现 分发任务的机制，从而根据具体的任务，进行调优分配。

**Comment by xiaolaosao** [comment]
感谢感谢，了解啦！
