### ISSUE TITLE
VS2015

### ISSUE THREAD

**Issue by SHU-FLYMAN** [ChunelFeng/CThreadPool#6]
如果VS2015要使用这个库，应该怎么操作？

**Comment by ChunelFeng** [comment]
您好，本项目默认采用cpp11版本，支持多平台编译，是支持 vs2015的，暂时不确定您遇到的问题是什么。
如果是 windows和 linux上结尾符不一致的问题，
请参考：https://github.com/ChunelFeng/CGraph/issues/12  中描述的内容和解决方法。

如果还不能解决的话，请随时和我们联系。

by the way，本项目实际上是 **https://github.com/ChunelFeng/CGraph** 项目的子项目，
如果有较多的多线程开发需求的话，优先 推荐查看 CGraph 项目，
那里包含了这个线程池的所有功能，版本较新，并且基于此实现了任务编排和参数传递等功能。

**Comment by SHU-FLYMAN** [comment]
Chunel
        好的，万分感谢。工作很棒！感谢！
        
        有什么问题随时与我联系和沟通，祝好！


2023-8-19
| |
曹建斌
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 8/19/2023 16:24 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [ChunelFeng/CThreadPool] VS2015 (Issue #6) |

您好，本项目默认采用cpp11版本，支持多平台编译，是支持 vs2015的，暂时不确定您遇到的问题是什么。
如果是 windows和 linux上结尾符不一致的问题，
请参考：ChunelFeng/CGraph#12 中描述的内容和解决方法。

如果还不能解决的话，请随时和我们联系。

by the way，本项目实际上是 https://github.com/ChunelFeng/CGraph 项目的子项目，
如果有较多的多线程开发需求的话，优先 推荐查看 CGraph 项目，
那里包含了这个线程池的所有功能，版本较新，并且基于此实现了任务编排和参数传递等功能。
