### ISSUE TITLE
std::condition_variable的wait_for问题

### ISSUE THREAD

**Issue by aijle** [ChunelFeng/CThreadPool#7]
依赖于系统时钟，改变系统时间会造成等待问题(gcc 10之前)。最简单的做法，使用boost库替换，虽然编译比较多，实际只依boost_thread和boost_chrono两个库。

**Comment by ChunelFeng** [comment]
你好，感谢您的的分享，gcc10之后修复了这个问题这事，我还真知道，哈哈。

之前是有了解过，故意改变系统时间会导致 wait的时间异常的情况。
但不是很确定什么情况下，会出现软件运行的时候，必须修改系统时间的情况。
比如，是人为修改，还是其他进程做出对应修改？

项目自身追求简单好用和可移植性，暂时不太想依赖boost中的内容。

**Comment by ChunelFeng** [comment]
今天稍微看了一下，如果担心 系统时间调整，导致cond_var 等待时间异常的话，
可以考虑使用 cond_var.wait_util(now + 10ms) 的思路来解决这个问题。

**Comment by aijle** [comment]
老版本的wait_util并不能解决这个问题，虽然可以指定使用单调时钟，但是内部还是转成了系统时钟的wait_for处理。这个情况在频繁校对时钟的环境下出现的比较频繁。知道有这么回事吧。
