### ISSUE TITLE
类继承关系的设计思路请教

### ISSUE THREAD

**Issue by 578223592** [ChunelFeng/CThreadPool#8]
项目里面这样弄继承关系的思想是？感觉设计的稍微有些复杂，可读性不是很好。
![88462fbf407dfb19ff358d8bc381100](https://github.com/ChunelFeng/CThreadPool/assets/65906820/e18b2e3b-20fc-4eda-bd2b-c8a522b62eb0)

**Comment by 578223592** [comment]
已经群中请教，故close

**Comment by ChunelFeng** [comment]
快去给色图点个 star，我以批主的身份命令你[/邪魅一笑]

https://github.com/ChunelFeng/CGraph

**Comment by 578223592** [comment]
> 快去给色图点个 star，我以批主的身份命令你[/邪魅一笑]
> 
> https://github.com/ChunelFeng/CGraph

收到！

**Comment by youarefree123** [comment]
> 已经群中请教，故close

老哥，可以群号可以发一下吗？

**Comment by ChunelFeng** [comment]
> > 已经群中请教，故close
> 
> 老哥，可以群号可以发一下吗？

欢迎添加我的个人微信（ChunelFeng），项目中也可以看到二维码。
