### ISSUE TITLE
低延迟的一些考虑

### ISSUE THREAD

**Issue by noobxinyu** [ChunelFeng/CThreadPool#9]
可以提供一个低延迟模式，让worker thread一直轮询。因为用cv的代价是挺大的。还可以考虑用无锁队列来传递信息。

**Comment by ChunelFeng** [comment]
你好，一直轮询可能引起空转，使用时候建议小心。

本项目通过调整 CGRAPH_PRIMARY_THREAD_BUSY_EPOCH 的值，达到一直轮询的效果，
如有使用需求，推荐使用 CStatus setConfig(const UThreadPoolConfig &config); 接口设置。
